#Applicatin Name
spring.application.name=Agial_Project_Management_system
# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/APMST_DB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=ENTER_YOUR_MYSQL_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#File upload size
pring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# GitHub Integration
github.token=ENTER_YOUR_GITHUB_TOKEN
github.username=ENTER_YOUR_GITHUB_USERNAME
github.repo=ENTER_YOUR_GITHUB_REPO_NAME

#Mail Request sending Servicespring.mail.host=smtp.gmail.com
spring.mail.port=ENTER_YOUR_MAIL_PORT
spring.mail.username=ENTER_YOUR_MAIL_USERNAME
spring.mail.password=ENTER_YOUR_MAIL_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true